### ISSUE TITLE
Infiltration model for new projects

### ISSUE THREAD

**Issue by MitchHeineman** [USEPA/SWMM-GUI#3]
The default infiltration model is Horton. I suggest changing to Modified Horton (or Modified G-A) to reflect that the modified methods are considered superior to the original methods.

**Comment by cbuahin** [comment]
@MitchHeineman, I believe this is already the case for v5.2.4,

**Comment by MitchHeineman** [comment]
If I do a clean install, the program creates C:\Users\myname\AppData\Roaming\EPASWMM\epaswmm5.ini with 144 lines of content. If I then open the GUI and select Project | Defaults, the program shows Horton as the default infiltration model. I can edit my preferences there and the program then writes 45 lines to the .ini file with additional sections for [Labels] and [Defaults]. Unless I change and save the infiltration method in the Defaults dialog, the default infiltration method remains Horton. As the .ini file does not get deleted when the user installs a new version, the previous setting gets carried over for a new installation.

> [Labels]
> Increment=1
> Rain Gage=
> ...
> [Defaults]
> SUBCATCH_AREA=5
> ...
> INFILTRATION=HORTON
> ROUTING_MODEL=DYNWAVE
> ...
