### ISSUE TITLE
need to check for zeroed-out map dimensions

### ISSUE THREAD

**Issue by MikeGregory-Canada** [USEPA/SWMM-GUI#9]
An infinitely looping floating point division by zero error results when you open an input file that has zeroed-out map dimensions. Give it a try…
[MAP]
DIMENSIONS       0                0                0                0               
UNITS            Feet

**Comment by LRossman** [comment]
I believe this bug was fixed back in 2021 with release 5.2.0. I can't duplicate it with v5.2.4 so I suggest this issue be closed.
